/**
 * Unity Adapter for Layouteer
 *
 * Generates a C# Editor script that, when run in Unity, creates the UI
 * hierarchy described by the Layouteer export JSON.
 *
 * WHY an Editor script instead of .prefab YAML?
 * Unity's .prefab format relies on fileID/GUID cross-references that are
 * nearly impossible to generate correctly outside the Unity Editor. This
 * script approach is reliable, undoable, and lets you tweak the result.
 *
 * Usage in Unity:
 *   1. Place the generated .cs file in an Editor/ folder
 *   2. Tools > Layouteer > Generate UI from JSON
 *   3. Select the .json export file when prompted
 *
 * Requires: TextMeshPro (for text), Unity 2022+
 */

export function adaptToUnity(exportJson) {
  const layout = exportJson.layout;
  if (!layout) return { error: 'No layout data' };

  const elements = flattenElements(layout);
  const byRole = groupByRole(elements);

  let code = '';
  code += `// Auto-generated by Layouteer — Unity UI Builder\n`;
  code += `// Edit the JSON source, NOT this file.\n`;
  code += `// Place in an Editor/ folder, then run Tools > Layouteer > Generate UI\n\n`;

  code += `using UnityEngine;\n`;
  code += `using UnityEngine.UI;\n`;
  code += `using UnityEngine.UIElements;\n`;
  code += `using TMPro;\n`;
  code += `using UnityEditor;\n`;
  code += `using System.IO;\n\n`;

  code += `public static class LayouteerUIBuilder\n`;
  code += `{\n`;

  code += `    [MenuItem("Tools/Layouteer/Generate UI from JSON")]\n`;
  code += `    public static void GenerateFromJson()\n`;
  code += `    {\n`;
  code += `        string path = EditorUtility.OpenFilePanel("Select Layouteer Export", "", "json");\n`;
  code += `        if (string.IsNullOrEmpty(path)) return;\n\n`;
  code += `        string json = File.ReadAllText(path);\n`;
  code += `        var data = JsonUtility.FromJson<LayoutData>(json);\n`;
  code += `        if (data?.layout == null) { Debug.LogError("Invalid Layouteer JSON"); return; }\n\n`;
  code += `        GenerateUI(data.layout);\n`;
  code += `    }\n\n`;

  // Entry point
  code += `    public static void GenerateUI(LayoutNode root)\n`;
  code += `    {\n`;
  code += `        // Create root canvas\n`;
  code += `        var canvasGO = new GameObject(root.name ?? "UI Canvas");\n`;
  code += `        var canvas = canvasGO.AddComponent<Canvas>();\n`;
  code += `        canvas.renderMode = RenderMode.ScreenSpaceOverlay;\n`;
  code += `        canvasGO.AddComponent<CanvasScaler>();\n`;
  code += `        canvasGO.AddComponent<GraphicRaycaster>();\n\n`;
  code += `        Undo.RegisterCreatedObjectUndo(canvasGO, "Create Layouteer UI");\n\n`;
  code += `        var rectTransform = canvasGO.GetComponent<RectTransform>();\n`;
  code += `        rectTransform.sizeDelta = new Vector2(${layout.props?.width || 1280}f, ${layout.props?.height || 720}f);\n\n`;
  code += `        BuildChildren(root, canvasGO.transform, ${layout.props?.width || 1280}f, ${layout.props?.height || 720}f);\n`;
  code += `    }\n\n`;

  // BuildChildren recursive function
  code += `    static void BuildChildren(LayoutNode node, Transform parent, float parentW, float parentH)\n`;
  code += `    {\n`;
  code += `        if (node.children == null) return;\n`;
  code += `        foreach (var child in node.children)\n`;
  code += `        {\n`;
  code += `            if (child == null) continue;\n`;
  code += `            CreateElement(child, parent, parentW, parentH);\n`;
  code += `        }\n`;
  code += `    }\n\n`;

  // CreateElement function
  code += `    static void CreateElement(LayoutNode node, Transform parent, float parentW, float parentH)\n`;
  code += `    {\n`;
  code += `        var go = new GameObject(node.name ?? "Element");\n`;
  code += `        go.transform.SetParent(parent, false);\n`;
  code += `        var rt = go.AddComponent<RectTransform>();\n\n`;

  // Position & anchor mapping
  code += `        SetAnchorAndPosition(rt, node, parentW, parentH);\n\n`;

  // Element type-specific components
  code += `        switch (node.type)\n`;
  code += `        {\n`;

  // Panel
  code += `            case "panel":\n`;
  code += `                var img = go.AddComponent<Image>();\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.backgroundColor))\n`;
  code += `                    img.color = ParseColor(node.props.backgroundColor);\n`;
  code += `                break;\n\n`;

  // Text
  code += `            case "text":\n`;
  code += `                var tmp = go.AddComponent<TextMeshProUGUI>();\n`;
  code += `                tmp.text = node.props?.text ?? "";\n`;
  code += `                if (node.props?.fontSize > 0) tmp.fontSize = node.props.fontSize;\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.color)) tmp.color = ParseColor(node.props.color);\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.fontFamily)) tmp.font = Resources.Load<TMP_FontAsset>(node.props.fontFamily);\n`;
  code += `                tmp.alignment = GetAlignment(node.props?.textAlign);\n`;
  code += `                break;\n\n`;

  // Image
  code += `            case "image":\n`;
  code += `                var rawImg = go.AddComponent<RawImage>();\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.src))\n`;
  code += `                {\n`;
  code += `                    string assetPath = ResolveAssetPath(node.props.src);\n`;
  code += `                    var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(assetPath);\n`;
  code += `                    if (tex != null) rawImg.texture = tex;\n`;
  code += `                }\n`;
  code += `                if (node.props?.opacity.HasValue == true) rawImg.color = new Color(1,1,1,node.props.opacity.Value);\n`;
  code += `                break;\n\n`;

  // Button
  code += `            case "button":\n`;
  code += `                var btn = go.AddComponent<Button>();\n`;
  code += `                var btnImg = go.AddComponent<Image>();\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.backgroundColor))\n`;
  code += `                    btnImg.color = ParseColor(node.props.backgroundColor);\n`;
  code += `                // Label as child TextMeshPro\n`;
  code += `                var labelGO = new GameObject("Label");\n`;
  code += `                labelGO.transform.SetParent(go.transform, false);\n`;
  code += `                var labelTMP = labelGO.AddComponent<TextMeshProUGUI>();\n`;
  code += `                labelTMP.text = node.props?.label ?? node.props?.text ?? "Button";\n`;
  code += `                if (node.props?.fontSize > 0) labelTMP.fontSize = node.props.fontSize;\n`;
  code += `                if (!string.IsNullOrEmpty(node.props?.color)) labelTMP.color = ParseColor(node.props.color);\n`;
  code += `                labelTMP.alignment = TextAlignmentOptions.Center;\n`;
  code += `                // Stretch label to fill button\n`;
  code += `                var labelRt = labelGO.GetComponent<RectTransform>();\n`;
  code += `                labelRt.anchorMin = Vector2.zero;\n`;
  code += `                labelRt.anchorMax = Vector2.one;\n`;
  code += `                labelRt.sizeDelta = Vector2.zero;\n`;
  code += `                break;\n\n`;

  // Scroll
  code += `            case "scroll":\n`;
  code += `                var scroll = go.AddComponent<ScrollRect>();\n`;
  code += `                var viewport = new GameObject("Viewport").AddComponent<RectTransform>();\n`;
  code += `                viewport.SetParent(rt, false);\n`;
  code += `                viewport.gameObject.AddComponent<Mask>();\n`;
  code += `                scroll.viewport = viewport;\n`;
  code += `                scroll.horizontal = node.props?.scrollDirection != "vertical";\n`;
  code += `                scroll.vertical = node.props?.scrollDirection != "horizontal";\n`;
  code += `                break;\n\n`;

  code += `        }\n\n`;

  // Recurse children
  code += `        BuildChildren(node, go.transform,\n`;
  code += `            node.props?.width ?? parentW,\n`;
  code += `            node.props?.height ?? parentH);\n`;
  code += `    }\n\n`;

  // SetAnchorAndPosition helper
  code += `    static void SetAnchorAndPosition(RectTransform rt, LayoutNode node, float parentW, float parentH)\n`;
  code += `    {\n`;
  code += `        float x = node.props?.x ?? 0;\n`;
  code += `        float y = node.props?.y ?? 0;\n`;
  code += `        float w = node.props?.width ?? 200;\n`;
  code += `        float h = node.props?.height ?? 100;\n\n`;
  code += `        string anchor = node.anchor ?? "top-left";\n`;
  code += `        switch (anchor)\n`;
  code += `        {\n`;
  code += `            case "top-left":\n`;
  code += `                rt.anchorMin = new Vector2(0, 1); rt.anchorMax = new Vector2(0, 1);\n`;
  code += `                rt.pivot = new Vector2(0, 1);\n`;
  code += `                rt.anchoredPosition = new Vector2(x, -y);\n`;
  code += `                break;\n`;
  code += `            case "top-center":\n`;
  code += `                rt.anchorMin = new Vector2(0.5f, 1); rt.anchorMax = new Vector2(0.5f, 1);\n`;
  code += `                rt.pivot = new Vector2(0.5f, 1);\n`;
  code += `                rt.anchoredPosition = new Vector2(x, -y);\n`;
  code += `                break;\n`;
  code += `            case "top-right":\n`;
  code += `                rt.anchorMin = new Vector2(1, 1); rt.anchorMax = new Vector2(1, 1);\n`;
  code += `                rt.pivot = new Vector2(1, 1);\n`;
  code += `                rt.anchoredPosition = new Vector2(-(parentW - x - w), -y);\n`;
  code += `                break;\n`;
  code += `            case "center-left":\n`;
  code += `                rt.anchorMin = new Vector2(0, 0.5f); rt.anchorMax = new Vector2(0, 0.5f);\n`;
  code += `                rt.pivot = new Vector2(0, 0.5f);\n`;
  code += `                rt.anchoredPosition = new Vector2(x, -(y + h / 2 - parentH / 2));\n`;
  code += `                break;\n`;
  code += `            case "center":\n`;
  code += `                rt.anchorMin = new Vector2(0.5f, 0.5f); rt.anchorMax = new Vector2(0.5f, 0.5f);\n`;
  code += `                rt.pivot = new Vector2(0.5f, 0.5f);\n`;
  code += `                rt.anchoredPosition = new Vector2(x + w / 2 - parentW / 2, y + h / 2 - parentH / 2);\n`;
  code += `                break;\n`;
  code += `            case "center-right":\n`;
  code += `                rt.anchorMin = new Vector2(1, 0.5f); rt.anchorMax = new Vector2(1, 0.5f);\n`;
  code += `                rt.pivot = new Vector2(1, 0.5f);\n`;
  code += `                rt.anchoredPosition = new Vector2(-(parentW - x - w), -(y + h / 2 - parentH / 2));\n`;
  code += `                break;\n`;
  code += `            case "bottom-left":\n`;
  code += `                rt.anchorMin = new Vector2(0, 0); rt.anchorMax = new Vector2(0, 0);\n`;
  code += `                rt.pivot = new Vector2(0, 0);\n`;
  code += `                rt.anchoredPosition = new Vector2(x, y);\n`;
  code += `                break;\n`;
  code += `            case "bottom-center":\n`;
  code += `                rt.anchorMin = new Vector2(0.5f, 0); rt.anchorMax = new Vector2(0.5f, 0);\n`;
  code += `                rt.pivot = new Vector2(0.5f, 0);\n`;
  code += `                rt.anchoredPosition = new Vector2(x, y);\n`;
  code += `                break;\n`;
  code += `            case "bottom-right":\n`;
  code += `                rt.anchorMin = new Vector2(1, 0); rt.anchorMax = new Vector2(1, 0);\n`;
  code += `                rt.pivot = new Vector2(1, 0);\n`;
  code += `                rt.anchoredPosition = new Vector2(-(parentW - x - w), y);\n`;
  code += `                break;\n`;
  code += `        }\n\n`;
  code += `        rt.sizeDelta = new Vector2(w, h);\n`;
  code += `    }\n\n`;

  // ParseColor helper
  code += `    static Color ParseColor(string hex)\n`;
  code += `    {\n`;
  code += `        if (string.IsNullOrEmpty(hex)) return Color.white;\n`;
  code += `        hex = hex.TrimStart('#');\n`;
  code += `        if (hex.Length < 6) return Color.white;\n`;
  code += `        byte r = System.Convert.ToByte(hex.Substring(0, 2), 16);\n`;
  code += `        byte g = System.Convert.ToByte(hex.Substring(2, 2), 16);\n`;
  code += `        byte b = System.Convert.ToByte(hex.Substring(4, 2), 16);\n`;
  code += `        byte a = hex.Length >= 8 ? System.Convert.ToByte(hex.Substring(6, 2), 16) : (byte)255;\n`;
  code += `        return new Color32(r, g, b, a);\n`;
  code += `    }\n\n`;

  // ResolveAssetPath helper
  code += `    static string ResolveAssetPath(string src)\n`;
  code += `    {\n`;
  code += `        // Convert asset:// URIs to Unity asset paths\n`;
  code += `        if (src.StartsWith("asset://"))\n`;
  code += `            src = "Assets/" + src.Substring(8);\n`;
  code += `        return src;\n`;
  code += `    }\n\n`;

  // GetAlignment helper
  code += `    static TextAlignmentOptions GetAlignment(string align)\n`;
  code += `    {\n`;
  code += `        switch (align)\n`;
  code += `        {\n`;
  code += `            case "left": return TextAlignmentOptions.TopLeft;\n`;
  code += `            case "center": return TextAlignmentOptions.TopCenter;\n`;
  code += `            case "right": return TextAlignmentOptions.TopRight;\n`;
  code += `            default: return TextAlignmentOptions.TopLeft;\n`;
  code += `        }\n`;
  code += `    }\n`;

  // JSON data model
  code += `}\n\n`;
  code += `[System.Serializable]\n`;
  code += `public class LayoutData\n`;
  code += `{\n`;
  code += `    public LayoutNode layout;\n`;
  code += `}\n\n`;
  code += `[System.Serializable]\n`;
  code += `public class LayoutNode\n`;
  code += `{\n`;
  code += `    public string id;\n`;
  code += `    public string name;\n`;
  code += `    public string type;\n`;
  code += `    public string role;\n`;
  code += `    public string anchor;\n`;
  code += `    public NodeProps props;\n`;
  code += `    public LayoutNode[] children;\n`;
  code += `}\n\n`;
  code += `[System.Serializable]\n`;
  code += `public class NodeProps\n`;
  code += `{\n`;
  code += `    public float x;\n`;
  code += `    public float y;\n`;
  code += `    public float width;\n`;
  code += `    public float height;\n`;
  code += `    public string text;\n`;
  code += `    public string label;\n`;
  code += `    public string backgroundColor;\n`;
  code += `    public string color;\n`;
  code += `    public float fontSize;\n`;
  code += `    public string fontFamily;\n`;
  code += `    public string textAlign;\n`;
  code += `    public float borderRadius;\n`;
  code += `    public string src;\n`;
  code += `    public string objectFit;\n`;
  code += `    public float opacity;\n`;
  code += `    public string scrollDirection;\n`;
  code += `}\n`;

  return code;
}

function flattenElements(node) {
  const result = [];
  if (!node) return result;
  result.push(node);
  if (node.children) {
    for (const child of node.children) {
      if (typeof child === 'object') {
        result.push(...flattenElements(child));
      }
    }
  }
  return result;
}

function groupByRole(elements) {
  const map = {};
  for (const el of elements) {
    if (el.role) {
      if (!map[el.role]) map[el.role] = [];
      map[el.role].push(el);
    }
  }
  return map;
}

export function exportToUnity(exportJson) {
  return adaptToUnity(exportJson);
}
