/**
 * Unreal Engine 5 UMG Adapter for Layouteer
 * Generates a Python script that creates a UMG Widget Blueprint in Unreal Engine 5.
 *
 * Usage in Unreal Editor:
 *   1. Open the Unreal Editor
 *   2. Run: Tools > Execute Python Script
 *   3. Select the generated .py file
 *   4. A new Widget Blueprint asset is created at /Game/UI/LayouteerUI
 *
 * Requires: Unreal Engine 5.3+ with Python Editor Scripting enabled
 */

export function adaptToUnreal(exportJson) {
  const layout = exportJson.layout;
  if (!layout) return { error: 'No layout data' };

  const elements = flattenElements(layout);
  const byRole = groupByRole(elements);

  let code = '';
  code += `# Auto-generated by Layouteer — Unreal UMG Builder\n`;
  code += `# Edit the JSON source, NOT this file.\n`;
  code += `# Run in Unreal Editor: Tools > Execute Python Script\n\n`;

  code += `import unreal\n\n`;

  code += `# Asset paths\n`;
  code += `PACKAGE_PATH = "/Game/UI/LayouteerUI"\n`;
  code += `ASSET_NAME = "LW_LayouteerUI"\n\n`;

  code += `def create_widget():\n`;
  code += `    """Create or overwrite a Widget Blueprint from Layouteer data."""\n\n`;
  code += `    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()\n`;
  code += `    factory = unreal.WidgetBlueprintFactory()\n\n`;
  code += `    # Create the widget blueprint asset\n`;
  code += `    widget_asset = asset_tools.create_asset(\n`;
  code += `        asset_name=ASSET_NAME,\n`;
  code += `        package_path=PACKAGE_PATH,\n`;
  code += `        asset_class=unreal.WidgetBlueprint,\n`;
  code += `        factory=factory\n`;
  code += `    )\n\n`;
  code += `    if not widget_asset:\n`;
  code += `        unreal.log_error("Failed to create Widget Blueprint")\n`;
  code += `        return\n\n`;
  code += `    unreal.log("Created Widget Blueprint: " + PACKAGE_PATH + "/" + ASSET_NAME)\n\n`;

  code += `    # Get the widget tree\n`;
  code += `    widget_tree = widget_asset.get_widget_tree()\n`;
  code += `    root_widget = widget_tree.root_widget\n\n`;

  // Root canvas setup
  code += `    # Root is a CanvasPanel by default; set its size\n`;
  code += `    root_widget.set_editor_property("size", unreal.Vector2D(${layout.props?.width || 1280}, ${layout.props?.height || 720}))\n\n`;

  // Build all children
  code += `    # Build UI hierarchy\n`;
  code += `    build_children(widget_tree, root_widget, ${layout.props?.width || 1280}, ${layout.props?.height || 720})\n\n`;

  code += `    # Save the asset\n`;
  code += `    unreal.EditorAssetLibrary.save_asset(PACKAGE_PATH + "/" + ASSET_NAME)\n`;
  code += `    unreal.log("Layouteer UI widget saved successfully!")\n\n\n`;

  // BuildChildren function
  code += `def build_children(widget_tree, parent_widget, parent_w, parent_h):\n`;
  code += `    """Recursively build UI elements from the JSON layout data."""\n\n`;
  // We embed the layout JSON as a Python dict for simplicity
  code += `    # Layout data (embedded by Layouteer)\n`;
  code += `    layout = ${JSON.stringify(layout, null, 2).replace(/\n/g, '\n    ')}\n\n`;
  code += `    children = layout.get("children", [])\n`;
  code += `    for child_data in children:\n`;
  code += `        if not child_data:\n`;
  code += `            continue\n`;
  code += `        element = create_element(widget_tree, parent_widget, child_data, parent_w, parent_h)\n`;
  code += `        if element:\n`;
  code += `            # Recurse children\n`;
  code += `            child_children = child_data.get("children", [])\n`;
  code += `            if child_children:\n`;
  code += `                child_w = child_data.get("props", {}).get("width", parent_w)\n`;
  code += `                child_h = child_data.get("props", {}).get("height", parent_h)\n`;
  code += `                for grandchild in child_children:\n`;
  code += `                    create_element(widget_tree, element, grandchild, child_w, child_h)\n\n\n`;

  // CreateElement function  
  code += `def create_element(widget_tree, parent, node_data, parent_w, parent_h):\n`;
  code += `    """Create a single UMG widget from a Layouteer node."""\n`;
  code += `    node_type = node_data.get("type", "panel")\n`;
  code += `    node_name = node_data.get("name", "Element")\n`;
  code += `    props = node_data.get("props", {})\n`;
  code += `    anchor = node_data.get("anchor", "top-left")\n\n`;

  // Type mapping
  code += `    # Map type to Unreal widget class\n`;
  code += `    widget = None\n`;
  code += `    if node_type == "panel":\n`;
  code += `        widget = unreal.CanvasPanel()\n`;
  code += `    elif node_type == "text":\n`;
  code += `        widget = unreal.TextBlock()\n`;
  code += `        widget.set_editor_property("text", props.get("text", ""))\n`;
  code += `        if props.get("fontSize"):\n`;
  code += `            widget.set_editor_property("font_size", props["fontSize"])\n`;
  code += `        if props.get("color"):\n`;
  code += `            widget.set_editor_property("color_and_opacity", parse_color(props["color"]))\n`;
  code += `    elif node_type == "image":\n`;
  code += `        widget = unreal.Image()\n`;
  code += `        src = props.get("src", "")\n`;
  code += `        if src:\n`;
  code += `            # Convert asset:// URI to Unreal path\n`;
  code += `            asset_path = resolve_asset(src)\n`;
  code += `            tex = unreal.EditorAssetLibrary.load_asset(asset_path)\n`;
  code += `            if tex:\n`;
  code += `                brush = widget.get_editor_property("brush")\n`;
  code += `                brush.set_editor_property("resource_object", tex)\n`;
  code += `    elif node_type == "button":\n`;
  code += `        widget = unreal.Button()\n`;
  code += `        # Add label as child text block\n`;
  code += `        label = unreal.TextBlock()\n`;
  code += `        label.set_editor_property("text", props.get("label", props.get("text", "Button")))\n`;
  code += `        if props.get("color"):\n`;
  code += `            label.set_editor_property("color_and_opacity", parse_color(props["color"]))\n`;
  code += `        widget.set_editor_property("content", label)\n`;
  code += `    elif node_type == "scroll":\n`;
  code += `        widget = unreal.ScrollBox()\n`;
  code += `    else:\n`;
  code += `        widget = unreal.CanvasPanel()\n\n`;

  code += `    if not widget:\n`;
  code += `        return None\n\n`;

  code += `    # Set widget name (for editor clarity)\n`;
  code += `    widget.set_editor_property("name", node_name)\n\n`;

  code += `    # Add to parent's canvas slot\n`;
  code += `    widget_tree.add_widget(parent, widget)\n\n`;

  // Set anchor and position
  code += `    # Set anchor and position via CanvasPanelSlot\n`;
  code += `    slot = widget_tree.get_slot(widget)\n`;
  code += `    if slot:\n`;
  code += `        x = props.get("x", 0)\n`;
  code += `        y = props.get("y", 0)\n`;
  code += `        w = props.get("width", 200)\n`;
  code += `        h = props.get("height", 100)\n\n`;
  code += `        # Set anchors based on anchor enum\n`;
  code += `        anchors = get_anchors(anchor, parent_w, parent_h, x, y, w, h)\n`;
  code += `        slot.set_editor_property("anchors", anchors)\n`;
  code += `        slot.set_editor_property("offset_left", x)\n`;
  code += `        slot.set_editor_property("offset_top", y)\n`;
  code += `        slot.set_editor_property("offset_right", -(parent_w - x - w))\n`;
  code += `        slot.set_editor_property("offset_bottom", -(parent_h - y - h))\n\n`;

  // Background color for panels
  code += `    # Panel background via brush\n`;
  code += `    if node_type == "panel" and props.get("backgroundColor"):\n`;
  code += `        color = parse_color(props["backgroundColor"])\n`;
  code += `        brush = widget.get_editor_property("background")\n`;
  code += `        brush.set_editor_property("tint_color", color)\n\n`;

  code += `    return widget\n\n\n`;

  // Helper: parse_color
  code += `def parse_color(hex_str):\n`;
  code += `    """Convert #RRGGBB or #RRGGBBAA hex to LinearColor."""\n`;
  code += `    if not hex_str:\n`;
  code += `        return unreal.LinearColor(1, 1, 1, 1)\n`;
  code += `    hex_str = hex_str.lstrip("#")\n`;
  code += `    if len(hex_str) < 6:\n`;
  code += `        return unreal.LinearColor(1, 1, 1, 1)\n`;
  code += `    r = int(hex_str[0:2], 16) / 255.0\n`;
  code += `    g = int(hex_str[2:4], 16) / 255.0\n`;
  code += `    b = int(hex_str[4:6], 16) / 255.0\n`;
  code += `    a = int(hex_str[6:8], 16) / 255.0 if len(hex_str) >= 8 else 1.0\n`;
  code += `    return unreal.LinearColor(r, g, b, a)\n\n\n`;

  // Helper: resolve_asset
  code += `def resolve_asset(src):\n`;
  code += `    """Convert asset:// URI to Unreal asset path."""\n`;
  code += `    if src.startswith("asset://"):\n`;
  code += `        return "/Game/" + src[8:].rsplit(".", 1)[0]  # Strip extension\n`;
  code += `    return src\n\n\n`;

  // Helper: get_anchors
  code += `def get_anchors(anchor, parent_w, parent_h, x, y, w, h):\n`;
  code += `    """Convert Layouteer anchor to Unreal Anchors (min_x, min_y, max_x, max_y)."""\n`;
  code += `    anchor_map = {\n`;
  code += `        "top-left":       (0, 0, 0, 0),\n`;
  code += `        "top-center":     (0.5, 0, 0.5, 0),\n`;
  code += `        "top-right":      (1, 0, 1, 0),\n`;
  code += `        "center-left":    (0, 0.5, 0, 0.5),\n`;
  code += `        "center":         (0.5, 0.5, 0.5, 0.5),\n`;
  code += `        "center-right":   (1, 0.5, 1, 0.5),\n`;
  code += `        "bottom-left":    (0, 1, 0, 1),\n`;
  code += `        "bottom-center":  (0.5, 1, 0.5, 1),\n`;
  code += `        "bottom-right":   (1, 1, 1, 1),\n`;
  code += `    }\n`;
  code += `    vals = anchor_map.get(anchor, (0, 0, 0, 0))\n`;
  code += `    return unreal.Anchors(*vals)\n\n\n`;

  // Entry point
  code += `if __name__ == "__main__":\n`;
  code += `    create_widget()\n`;

  return code;
}

function flattenElements(node) {
  const result = [];
  if (!node) return result;
  result.push(node);
  if (node.children) {
    for (const child of node.children) {
      if (typeof child === 'object') {
        result.push(...flattenElements(child));
      }
    }
  }
  return result;
}

function groupByRole(elements) {
  const map = {};
  for (const el of elements) {
    if (el.role) {
      if (!map[el.role]) map[el.role] = [];
      map[el.role].push(el);
    }
  }
  return map;
}

export function exportToUnreal(exportJson) {
  return adaptToUnreal(exportJson);
}
